name: shopping_list_app
description: A simple Flutter app to manage shopping lists

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.0.5
  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
